// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class ChooseTypeTests {
    private WebDriver driver;
    JavascriptExecutor js;


    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;

        // Test name: test_choose_type_appear_hours
        // Step # | name | target | value | comment
        // 1 | open | / |  |
        driver.get("http://localhost:5000/");

        // 2 | setWindowSize | 1920x1033 |  |
        driver.manage().window().setSize(new Dimension(1920, 1033));
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testSelectForecastAppearHours() {

        // 3 | select | id=type | value=forecast |
        WebElement dropdown = driver.findElement(By.id("type"));
        dropdown.findElement(By.cssSelector("*[value='forecast']")).click();

        // 4 | assertElementPresent | xpath=//input[@id='hours' and @required] |  |
        List<WebElement> elements = driver.findElements(By.xpath("//input[@id=\'hours\' and @required]"));
        assert (elements.size() > 0);
    }

    @Test
    public void testSelectHistoryAppearHours() {

        // 3 | select | id=type | value=history |
        WebElement dropdown = driver.findElement(By.id("type"));
        dropdown.findElement(By.cssSelector("*[value='history']")).click();

        // 4 | assertElementPresent | xpath=//input[@id='hours' and @required] |  |
        List<WebElement> elements = driver.findElements(By.xpath("//input[@id=\'hours\' and @required]"));
        assert (elements.size() > 0);
    }
}
