// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class MessagesTests {

    private WebDriver driver;
    JavascriptExecutor js;


    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;

        // Test name: test_choose_type_appear_hours
        // Step # | name | target | value | comment
        // 1 | open | / |  |
        driver.get("http://localhost:5000/");

        // 2 | setWindowSize | 1920x1033 |  |
        driver.manage().window().setSize(new Dimension(1920, 1033));
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testSubmitSuccessMessageNoErrorMessage() {

        // 3 | click | id=latitude |  |
        driver.findElement(By.id("latitude")).click();

        // 4 | type | id=latitude | 39.160489 |
        driver.findElement(By.id("latitude")).sendKeys("39.160489");

        // 5 | type | id=longitude | 8.548239 |
        driver.findElement(By.id("longitude")).sendKeys("8.548239");

        // 6 | click | id=get_btn |  |
        driver.findElement(By.id("get_btn")).click();

        // 7 | assertElementPresent | xpath=//div[@id='success_message' and @class='alert alert-success'] |  |
        List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'success_message\' and @class=\'alert alert-success\']"));
        assert(elements.size() > 0);

        // 8 | assertElementNotPresent | xpath=//div[@id='error_message' and @class='alert alert-danger'] |  |
        elements = driver.findElements(By.xpath("//div[@id=\'error_message\']"));
        assert(elements.size() == 0);
    }

    @Test
    public void testSubmitErrorMessageNoSuccessMessage() {

        // 3 | click | id=latitude |  |
        driver.findElement(By.id("latitude")).click();

        // 4 | type | id=latitude | 0 |
        driver.findElement(By.id("latitude")).sendKeys("0");

        // 5 | click | id=longitude |  |
        driver.findElement(By.id("longitude")).click();

        // 6 | type | id=longitude | 0 |
        driver.findElement(By.id("longitude")).sendKeys("0");

        // 7 | click | id=get_btn |  |
        driver.findElement(By.id("get_btn")).click();

        // 8 | assertElementPresent | xpath=//div[@id='error_message' and @class='alert alert-danger'] |  |
        List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'error_message\' and @class=\'alert alert-danger\']"));
        assert(elements.size() > 0);

        // 9 | assertElementNotPresent | xpath=//div[@id='success_message'] |  |
        elements = driver.findElements(By.xpath("//div[@id=\'success_message\']"));
        assert(elements.size() == 0);
    }
}
